### ISSUE TITLE
Don't include `default` in aliased types

### ISSUE THREAD

**Issue by criccomini** [recap-build/recap#337]
I think (but haven't verified) that `default` is currently included as part of an aliased type. I think this should be excluded if it's currently included.

```yaml
type: struct
fields:
  - name: foo
    alias: build.recap.Foo
    type: string
    default: some_default_string
  - name: bar
    type: build.recap.Foo
```

I think `bar` should not have `default` after the alias is resolved.
