### ISSUE TITLE
Remove `[]` union syntactic sugar

### ISSUE THREAD

**Issue by criccomini** [recap-build/recap#339]
When Recap supports `optional: true` I'm thinking of removing the `type: ["int32", "float32"]` syntactic sugar. The vast majority of `union` usage was for `type: ["null", ...]` to create nullable fields. Now that we have `optional`, I don't feel the added complexity of supporting array shorthand is worth it.

Instead, all unions will be defined as:

```yaml
type: struct
fields:
  - type: union
    types: ["int32", "float32"]
```

This style will no longer be supported:

```yaml
type: struct
fields:
  - type: ["int32", "float32"]
```

WDYT? @adrianisk @gwukelic @cpard
